export function cleanBiomeName(name) {
    return (name || '').replace(/[^\w\s]/gi, '').trim().toLowerCase();
}

export const DEFAULT_BIOME_FOG_CONFIGS = {
    'Archipelago': {
        enabled: true,
        intensity: 0.85,
        opacity: 0.75,
        heightOffset: 0,
        layerSpacing: 16,
        driftSpeed: 1.0,
        turbulence: 1.0,
        nearFade: 10,
        farFade: 1750,
        distNear: 80,
        distFar: 1800,
        distDensity: 0.90,
        distAltScale: 1.2,
        color: '#dbeafe',
        colorDusk: '#fed7aa',
        colorNight: '#1e293b'
    },
    'Ghibli Land': {
        enabled: true,
        intensity: 0.90,
        opacity: 0.80,
        heightOffset: -4,
        layerSpacing: 14,
        driftSpeed: 0.8,
        turbulence: 0.9,
        nearFade: 10,
        farFade: 1750,
        distNear: 60,
        distFar: 2000,
        distDensity: 0.95,
        distAltScale: 1.0,
        color: '#ecfdf5',
        colorDusk: '#ffedd5',
        colorNight: '#0f172a'
    },
    'Crystal Mountains': {
        enabled: true,
        intensity: 0.95,
        opacity: 0.85,
        heightOffset: 10,
        layerSpacing: 18,
        driftSpeed: 1.2,
        turbulence: 1.2,
        nearFade: 15,
        farFade: 1600,
        distNear: 50,
        distFar: 1600,
        distDensity: 1.10,
        distAltScale: 1.5,
        color: '#e0e7ff',
        colorDusk: '#fbcfe8',
        colorNight: '#1e1b4b'
    },
    'Giant Pines': {
        enabled: true,
        intensity: 0.88,
        opacity: 0.78,
        heightOffset: -2,
        layerSpacing: 15,
        driftSpeed: 0.9,
        turbulence: 0.95,
        nearFade: 10,
        farFade: 1800,
        distNear: 70,
        distFar: 1900,
        distDensity: 0.92,
        distAltScale: 1.1,
        color: '#dcfce7',
        colorDusk: '#fef3c7',
        colorNight: '#064e3b'
    },
    'Jungle Island': {
        enabled: true,
        intensity: 0.92,
        opacity: 0.82,
        heightOffset: -6,
        layerSpacing: 12,
        driftSpeed: 0.7,
        turbulence: 0.85,
        nearFade: 10,
        farFade: 1750,
        distNear: 50,
        distFar: 1700,
        distDensity: 1.05,
        distAltScale: 1.0,
        color: '#d1fae5',
        colorDusk: '#fde68a',
        colorNight: '#022c22'
    },
    'Magical Islands': {
        enabled: true,
        intensity: 0.98,
        opacity: 0.90,
        heightOffset: 8,
        layerSpacing: 20,
        driftSpeed: 1.4,
        turbulence: 1.3,
        nearFade: 12,
        farFade: 1650,
        distNear: 40,
        distFar: 1500,
        distDensity: 1.15,
        distAltScale: 1.6,
        color: '#fae8ff',
        colorDusk: '#f472b6',
        colorNight: '#3b0764'
    },
    'Dunes & Canyons': {
        enabled: true,
        intensity: 0.75,
        opacity: 0.65,
        heightOffset: 2,
        layerSpacing: 14,
        driftSpeed: 1.5,
        turbulence: 1.4,
        nearFade: 15,
        farFade: 1850,
        distNear: 90,
        distFar: 2100,
        distDensity: 0.80,
        distAltScale: 1.3,
        color: '#fef3c7',
        colorDusk: '#fb923c',
        colorNight: '#451a03'
    },
    'North Pole Ice': {
        enabled: true,
        intensity: 0.90,
        opacity: 0.85,
        heightOffset: -5,
        layerSpacing: 15,
        driftSpeed: 0.9,
        turbulence: 1.0,
        nearFade: 10,
        farFade: 1700,
        distNear: 60,
        distFar: 1800,
        distDensity: 1.00,
        distAltScale: 1.1,
        color: '#e0f2fe',
        colorDusk: '#c7d2fe',
        colorNight: '#0f172a'
    }
};
